### PR TITLE
Visitor pattern implementation

### PR DESCRIPTION
**Pull request by tristanlatr**
Fixes https://github.com/NiklasRosenstein/docspec/discussions/22

I've created the `PrintVisitor` and the `FilterVisitor` such that you can eventually deprecate `filter_visit()` and/or `visit()` functions.

### CODE REVIEW

**Comment by tristanlatr** [comment]
OK, this `mypy` thing is getting me crazy. 

I'm not sure why it founds an error : 


```
  captured stdout:

      docspec-python/.venv-test/lib/python3.7/site-packages/docspec/__init__.py:57: error: Library stubs not installed for "termcolor" (or incompatible with Python 3.7)
      docspec-python/.venv-test/lib/python3.7/site-packages/docspec/__init__.py:57: note: Hint: "python3 -m pip install types-termcolor"
      docspec-python/.venv-test/lib/python3.7/site-packages/docspec/__init__.py:57: note: (or run "mypy --install-types" to install all missing stub packages)
      docspec-python/.venv-test/lib/python3.7/site-packages/docspec/__init__.py:57: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
      Found 1 error in 1 file (checked 5 source files)

Ran 1 test(s) in 1.226s (0 passed, 0 skipped, 1 failed, 0 error(s)). FAILED
```

The required library seems to be listed in the setup.py

**Comment by NiklasRosenstein** [comment]
Hm I'll look into that, not sure what's going on there.

**Comment by NiklasRosenstein** [comment]
Thanks for the contribution @tristanlatr !

Though I have to say I'm not a big fan of including these classes into the package. The ApiObject tree is easy to traverse recursively, and if your use case really benefits from the visitor pattern then it is trivial to implement close to the point of usage.

**Comment by tristanlatr** [comment]
The pattern ca significantly reduce the complexity of the tree traversal in many ways. For instance it's really easy to implement a stack of objects, pushing it on the visit method and poping it on the depart method. This mechanism is really help full to code solid builders. 

You are right that some could use this without it being available by default. But the majority of the library users will use the provided functions `visit` or `filter_visit`, or will walk the tree manually. 

Providing a correct visitor pattern implementation will - maybe - make people's code more readable.

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr , since you've started working on `pydocspec` and adding the visitor classes there, I'm going to close out this PR, okay? :)

Cheers

**Comment by tristanlatr** [comment]
That's alright :-)

**Pull request closed without merging**
