### PR TITLE
breaking change: harden requirements of spec

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
by requiring a `location` even on `Decoration` and `Argument` objects, and the location is no longer optional. Rearrange the argument the Python classes such that the `location` argument comes first, always

### CODE REVIEW

**Comment by tristanlatr** [comment]
Do you absolutely need to change the arguments order? I’de argue that the older order made more sens to me since the most fundamental field of a object is it’s name, not it’s location.

**Comment by NiklasRosenstein** [comment]
The location is now shared also between Argument and Decoration, making it more common than name as Decoration doesn't have it. But then again, it's only one exception I suppose. Would you have a large number of instantiations to update?

**Comment by tristanlatr** [comment]
Capture d’écran, le 2022-02-25 à 14 48 52

> Would you have a large number of instantiations to update?

I have about 30 instanciations, actually more than that... A lot of them are using keyword arguments, so that's not too bad. 

But still, I feel like this change is not worth it because we can harden requirements of spec by making location non-optional and keeping it's position, and the result will be the same. 

The rationale could be that if the object has a name, then the name is the first arg and the location second, else, the location is the first argument. But I agree that could be confusing, so i don't know what to think about it tbh.

**Comment by NiklasRosenstein** [comment]
@tristanlatr  It looks to me like you're using some kind of factory interface anyway; if that's correct you'd only need to update the implementation of those factory functions. Your point is correct that it's not necessary for narrowing the spec, but it's a consistency thing I would like to introduce at some point and when better than on the next major bump.

**Comment by tristanlatr** [comment]
@NiklasRosenstein, my factory returns new types, so we still need to instanciate them. So I doesn’t change a lot whether I’m using my factory or not. But anyway, I’ll change all parameters to be keyword based so I don’t have a bad surprise. Thanks

**Pull request merged**
