### PR TITLE
improvement: Bump black to >=23.1.0

### LINKED ISSUE #95: Update black dependency
**Is your feature request related to a problem? Please describe.**
I am using your library in a build flow. My IT department flagged the version of black being used as having a potential security problem. 

**Describe the solution you'd like**
Can the black dependency be updated from `^23.1.0` to `>=23.1.0`?

**Describe alternatives you've considered**
No other alternatives thought of.

### PR DESCRIPTION
**Pull request by mcintel**
Along with this, also needed to bump pydoc-markdown. And for good measure, added docs/_site to .gitignore so `slap run docs:build` won't show a bunch of new files to add.

### CODE REVIEW

**Comment by mcintel** [comment]
@NiklasRosenstein I didn't totally understand how to add the `.changelog/_unreleased.log`. If you can give me a tip, I'll be more than happy to add it.

**Comment by NiklasRosenstein** [comment]
Thanks for the contribution @mcintel! You can mimic the same format after generating a fresh uuid for the `id` field, or install `slap-cli` with Pip(x) and use ``slap changelog add -t improvement -d 'Bump black to `>=23.1.0`'``

**Comment by mcintel** [comment]
@NiklasRosenstein Ah, thanks for the info. I see that the verify failed. I'll try to repro and fix.

Thanks for this tool! It's super rad! :grin:

**Comment by NiklasRosenstein** [comment]
Glad you like it ❤️ 

Black needs to be pinned to a major version as the next major version will most likely have breaking formatting changes; as demonstrated by the Python 3.7 tests (which get a 23.x version and all the other tests get the latest 24.x version).

One workaround would be to run Black for linting in this project separately from the runtime dependency; but I would say we can just drop the 3.7 support all together since that Python version is no longer supported.

**Comment by eljulians** [comment]
Hey folks, any chance we could merge this? Having an older version of black is blocking for those downstream packages relying on e.g. poetry that doesn't allow to set overrides.

Thank you very much!

**Comment by mcintel** [comment]
Hey @eljulians. I got totally distracted with other things. The only thing holding this up is the 3.7 tests are failing. @NiklasRosenstein, just to confirm, you're okay with removing 3.7 from the test matrix, right?

**Comment by NiklasRosenstein** [comment]
Hi, yes I'm okay to drop 3.7

In on a vacation without computer access so unfortunately I won't be able to publish a new release until I'm back (2 weeks).

**Comment by mcintel** [comment]
> In on a vacation without computer access so unfortunately, I won't be able to publish a new release until I'm back (2 weeks).

No rush on my side. The GH actions haven't kicked off yet, so I'm not totally sure I addressed all the failures.

**Comment by mcintel** [comment]
Hi @NiklasRosenstein. Hope you had an awesome vacation!

I'm having a little difficulty with the checks. I can't remember how I fixed it, but the "Insert in the Pull Request URL into new changelog entries" is complaining that .changelog is a readonly directory. Also, I see the 3.7 tests listed as waiting to be run; I had thought removing them from the workflow python matrix array would prevent them from running.

Can you help with getting these things working? Thanks!

**Comment by NiklasRosenstein** [comment]
I turned off the job for now, I can't look into the issue right now. 😄 It's not critical anyway.

Thanks a lot @mcintel !

**Comment by mcintel** [comment]
Thanks @NiklasRosenstein! Wish I could've spent more time figuring it out (busy as well). 😄

**Pull request merged**
