### PR TITLE
Add ApiObject.full_name property

### PR DESCRIPTION
**Pull request by tristanlatr**

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr , thanks for the suggestion.

Still pondering about this.. 🤔 This biases the API towards Python in a sense of the "content". Clearly it's already biased towards the constructs that need to be represented (e.g. decorators, keyword-only arguments, metaclasses), but that can be _extended_ while the full name construction would be _fixed_. The separator for C++ would be `::`, for PHP, JavaScript and TypeScript it would be `/`. I did actually plan to add a `docspec_typescript` at some point.

**Comment by tristanlatr** [comment]
Ok I see.

I could create a package, like `pydocspec` that would strictly respect the `docspec` specifications, but adding bunch of properties to classes and helpers functions to process python-specific Modules. 

What do you think ?

**Comment by NiklasRosenstein** [comment]
Yep, that sounds reasonable. I would think those could be a good fit to add into `docspec_python` (instead of a new `pydocspec` package).

**Comment by tristanlatr** [comment]
I thought `docspec_python` was the loader only.

**Comment by tristanlatr** [comment]
I'll finish the first version of `pydocspec` package, and then we'll see if it matches your expectations. 

I went with a separate repo because I want it to be usable without `docspec_python`, actually. 

But keeping the compatibility with `docspec`.

**Comment by NiklasRosenstein** [comment]
> I thought `docspec_python` was the loader only.

Yes, but I think some more Python _language_-specific functionality would makes sense in there. For example an `fqn()` method respectively instead of the `full_name` property.

```py
def fqn(obj: ApiObject) -> str:
  return '.'.join(o.name for o in obj.path)
```

Or for example

```py
def is_property(obj: ApiObject) -> bool:
  return isinstance(obj, Function) and any(dec.expr == '@property' for dec in obj.decorations)
```

Maybe not an `is_zope_interface()` because that is no longer just language specific, but also library specific,. But maybe into a `docspec_python.contrib.zope` module.

**Comment by tristanlatr** [comment]
Hi @NiklasRosenstein,

I see this contribution as extension of the `docspec` classes, specialized for the python language.
How it works it that it will convert each `docspec` class to it's augmented `pydocspec` version (with added properties and methods), instead of only providing helper methods. 

For the record, most the implementations are directly taken from `pydoctor` and adapted for `ApiObject` classes (which is much more easy than expected). The final goal is double: Do a massive refactoring of the pydoctor core model objects to adopt docspec/pydocspec and improve the pydoc-markdown API docs renderers (resolve relative links, understand attrs and dataclasses declarations, etc)

I'm not sure this contribution belongs to the `docspec_python` module, though, which is the python loader. It could be confusing to place it there. 

Let me a couple of days/week to finish a first version, then you'll tell me what you think. In the mean time you can check the code here: https://github.com/tristanlatr/pydocspec

And if everyones likes the idea, I'm ok for moving it into this repo. 

I'm tagging my fellows pydoctor dev such that they are aware of the proposition @adiroiban @mthuurne .

Anyway, it will add a LOT of new code. And it uses the visitor pattern ^^. 

Tell me what you think,

Thanks

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr ,

> The final goal is double: Do a massive refactoring of the pydoctor core model objects to adopt docspec/pydocspec and improve the pydoc-markdown API docs renderers (resolve relative links, understand attrs and dataclasses declarations, etc)

Yep, `docspec_python` does not sound like the right place for this. :) I love the ambition! The improvements you mention for pydoc-markdown are definitely on my todo list as well, just not finding the time to do it. I'd be appy to hold discussions about the design in the pydoc-markdown discussions / review PRs, though!

Looking forward to it.

For your awareness, I do have some plans that are somewhat related that I was hoping to get to in the next months. I just started a draft of my thoughts here: https://github.com/NiklasRosenstein/pydoc-markdown/discussions/211

Cheers,

**Pull request closed without merging**
